package com.subtitleedit.chat

import android.content.Context
import com.subtitleedit.chat.history.ChatHistoryDatabase
import com.subtitleedit.chat.history.ChatHistoryMessageEntity
import com.subtitleedit.chat.history.ChatHistorySessionEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

/**
 * Local, API-key-free conversation archive shared by chat and translation callers.
 *
 * Room stores each message independently, so adding a turn never rewrites an entire
 * conversation. The old SharedPreferences blob is imported once on first use.
 */
class ChatHistoryStore(context: Context) {
    data class Session(
        val id: String,
        val title: String,
        val type: String,
        val updatedAt: Long,
        val messages: List<ChatBackend.ChatMessage>
    )

    data class SessionSummary(
        val id: String,
        val title: String,
        val type: String,
        val updatedAt: Long
    )

    data class SearchResult(
        val sessionId: String,
        val title: String,
        val type: String,
        val updatedAt: Long,
        val position: Int,
        val role: String,
        val snippet: String
    )

    private val appContext = context.applicationContext
    private val database by lazy { ChatHistoryDatabase.getInstance(appContext) }
    private val legacyPreferences = appContext.getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE)
    private val migrationMutex = Mutex()

    /** Appends only the messages generated by the current request. */
    suspend fun append(
        id: String? = null,
        title: String,
        type: String,
        messages: List<ChatBackend.ChatMessage>
    ): String = withDatabase {
        if (messages.none { it.role == "user" || it.role == "assistant" }) return@withDatabase id.orEmpty()
        val sessionId = id ?: UUID.randomUUID().toString()
        val now = System.currentTimeMillis()
        database.runInTransaction {
            val dao = database.historyDao()
            val existing = dao.getSession(sessionId)
            dao.upsertSession(
                ChatHistorySessionEntity(
                    sessionId,
                    existing?.title ?: title.take(TITLE_MAX_CHARS).ifBlank { "未命名对话" },
                    existing?.type ?: normalizeType(type),
                    now
                )
            )
            val nextPosition = dao.nextPosition(sessionId)
            dao.insertMessages(messages.mapIndexed { index, message ->
                message.toEntity(sessionId, nextPosition + index)
            })
        }
        sessionId
    }

    suspend fun list(limit: Int = DEFAULT_LIST_LIMIT): List<SessionSummary> = withDatabase {
        database.historyDao().recentSessions(limit.coerceIn(1, MAX_LIST_LIMIT)).map { entity ->
            entity.toSummary()
        }
    }

    suspend fun load(id: String): Session? = withDatabase {
        val dao = database.historyDao()
        dao.getSession(id)?.let { session ->
            Session(
                id = session.id,
                title = session.title,
                type = session.type,
                updatedAt = session.updatedAt,
                messages = dao.getMessages(id).map(::messageFromEntity)
            )
        }
    }

    suspend fun recent(limit: Int = 10, type: String? = null): List<SessionSummary> = withDatabase {
        val requestedType = type?.takeIf(::isKnownType).orEmpty()
        database.historyDao().recentSessionsByType(
            requestedType,
            limit.coerceIn(1, MAX_LIST_LIMIT)
        ).map { entity -> entity.toSummary() }
    }

    suspend fun search(query: String, limit: Int = 10, type: String? = null): List<SearchResult> =
        withDatabase {
            val matchQuery = ftsMatchQuery(query)
            if (matchQuery.isBlank()) return@withDatabase emptyList()
            val requestedType = type?.takeIf(::isKnownType).orEmpty()
            val dao = database.historyDao()
            val boundedLimit = limit.coerceIn(1, MAX_LIST_LIMIT)
            val indexedResults = runCatching {
                dao.searchMessages(
                    matchQuery,
                    requestedType,
                    boundedLimit
                )
            }.getOrDefault(emptyList())
            val literalResults = dao.searchMessagesByContent(
                query.trim(),
                requestedType,
                boundedLimit
            )
            (indexedResults + literalResults)
                .distinctBy { row -> "${row.sessionId}:${row.position}" }
                .take(boundedLimit)
                .map { row ->
                    SearchResult(
                        sessionId = row.sessionId,
                        title = row.title,
                        type = row.type,
                        updatedAt = row.updatedAt,
                        position = row.position,
                        role = row.role,
                        snippet = row.snippet.orEmpty()
                    )
                }
        }

    suspend fun delete(id: String) = withDatabase {
        database.historyDao().deleteSession(id)
    }

    suspend fun clear() = withDatabase {
        database.historyDao().clearSessions()
    }

    private suspend fun <T> withDatabase(block: () -> T): T = withContext(Dispatchers.IO) {
        ensureLegacyMigrated()
        block()
    }

    private suspend fun ensureLegacyMigrated() = migrationMutex.withLock {
        if (legacyPreferences.getBoolean(KEY_ROOM_MIGRATED, false)) return
        val legacySessions = readLegacySessions()
        if (legacySessions.isNotEmpty()) {
            database.runInTransaction {
                val dao = database.historyDao()
                legacySessions.forEach { session ->
                    dao.deleteMessages(session.id)
                    dao.upsertSession(
                        ChatHistorySessionEntity(
                            session.id,
                            session.title.take(TITLE_MAX_CHARS).ifBlank { "未命名对话" },
                            normalizeType(session.type),
                            session.updatedAt
                        )
                    )
                    dao.insertMessages(session.messages.mapIndexed { index, message ->
                        message.toEntity(session.id, index)
                    })
                }
            }
        }
        legacyPreferences.edit()
            .remove(KEY_SESSIONS)
            .putBoolean(KEY_ROOM_MIGRATED, true)
            .apply()
    }

    private fun readLegacySessions(): List<Session> = runCatching {
        val root = JSONArray(legacyPreferences.getString(KEY_SESSIONS, "[]"))
        buildList {
            for (index in 0 until root.length()) {
                root.optJSONObject(index)?.let(::legacySessionFromJson)?.let(::add)
            }
        }
    }.getOrDefault(emptyList())

    private fun legacySessionFromJson(json: JSONObject): Session? {
        val id = json.optString("id")
        if (id.isBlank()) return null
        val messages = buildList {
            json.optJSONArray("messages")?.let { array ->
                for (index in 0 until array.length()) {
                    array.optJSONObject(index)?.let(::messageFromJson)?.let(::add)
                }
            }
        }
        return Session(
            id = id,
            title = json.optString("title", "未命名对话"),
            type = json.optString("type", TYPE_CHAT),
            updatedAt = json.optLong("updatedAt"),
            messages = messages
        )
    }

    private fun ChatBackend.ChatMessage.toEntity(
        sessionId: String,
        position: Int
    ) = ChatHistoryMessageEntity(
        sessionId,
        position,
        role,
        content,
        reasoningContent,
        JSONArray().apply {
            toolCalls.forEach { call ->
                put(JSONObject()
                    .put("id", call.id)
                    .put("name", call.name)
                    .put("arguments", call.arguments)
                )
            }
        }.toString(),
        toolCallId,
        toolName
    )

    private fun messageFromEntity(entity: ChatHistoryMessageEntity): ChatBackend.ChatMessage =
        ChatBackend.ChatMessage(
            role = entity.role,
            content = entity.content,
            reasoningContent = entity.reasoningContent,
            toolCalls = toolCallsFromJson(entity.toolCallsJson),
            toolCallId = entity.toolCallId,
            toolName = entity.toolName
        )

    private fun messageFromJson(json: JSONObject): ChatBackend.ChatMessage? {
        val role = json.optString("role")
        if (role.isBlank()) return null
        return ChatBackend.ChatMessage(
            role = role,
            content = json.optString("content"),
            reasoningContent = json.optString("reasoning"),
            toolCalls = toolCallsFromJson(json.optJSONArray("toolCalls")?.toString().orEmpty()),
            toolCallId = json.optString("toolCallId"),
            toolName = json.optString("toolName")
        )
    }

    private fun toolCallsFromJson(source: String): List<ChatBackend.ToolCall> = runCatching {
        val array = JSONArray(source.ifBlank { "[]" })
        buildList {
            for (index in 0 until array.length()) {
                val call = array.optJSONObject(index) ?: continue
                add(
                    ChatBackend.ToolCall(
                        id = call.optString("id"),
                        name = call.optString("name"),
                        arguments = call.optString("arguments")
                    )
                )
            }
        }
    }.getOrDefault(emptyList())

    private fun ChatHistorySessionEntity.toSummary() = SessionSummary(id, title, type, updatedAt)

    private fun ftsMatchQuery(query: String): String =
        Regex("[\\p{L}\\p{N}_]+").findAll(query)
            .map { match -> "\"${match.value.replace("\"", "\"\"")}\"" }
            .joinToString(" AND ")

    private fun normalizeType(type: String): String = type.takeIf(::isKnownType) ?: TYPE_CHAT

    private fun isKnownType(type: String): Boolean = type == TYPE_CHAT || type == TYPE_TRANSLATION

    companion object {
        const val TYPE_CHAT = "chat"
        const val TYPE_TRANSLATION = "translation"
        private const val PREFERENCES_NAME = "subtitle_edit_chat_history"
        private const val KEY_SESSIONS = "sessions"
        private const val KEY_ROOM_MIGRATED = "room_migrated"
        private const val DEFAULT_LIST_LIMIT = 100
        private const val MAX_LIST_LIMIT = 100
        private const val TITLE_MAX_CHARS = 64
    }
}
